// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace StarWarsRoutes.Infrastructure.Contracts.Entities
{
    public partial class Planets
    {
        public Planets()
        {
            RoutesDestinationPlanet = new HashSet<Routes>();
            RoutesOriginPlanet = new HashSet<Routes>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public decimal RebelInfluence { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }

        public virtual ICollection<Routes> RoutesDestinationPlanet { get; set; }
        public virtual ICollection<Routes> RoutesOriginPlanet { get; set; }
    }
}