// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace StarWarsRoutes.Infrastructure.Contracts.Entities
{
    public partial class PricesHistory
    {
        public int Id { get; set; }
        public decimal PricePerLunarDay { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}