// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace StarWarsRoutes.Infrastructure.Contracts.Entities
{
    public partial class Routes
    {
        public int Id { get; set; }
        public int OriginPlanetId { get; set; }
        public int DestinationPlanetId { get; set; }
        public decimal Distance { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }

        public virtual Planets DestinationPlanet { get; set; }
        public virtual Planets OriginPlanet { get; set; }
    }
}