// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using StarWarsRoutes.Infrastructure.Contracts.Entities;

namespace StarWarsRoutes.Infrastructure.Impl.DBContexts
{
    public partial class ImperialRoutesContext : DbContext
    {
        private readonly IConfiguration _configuration;

        public ImperialRoutesContext(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public ImperialRoutesContext(DbContextOptions<ImperialRoutesContext> options, IConfiguration configuration)
            : base(options)
        {
            _configuration = configuration;
        }

        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<PricesHistory> PricesHistory { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = _configuration.GetConnectionString("ImperialRoutes");
                optionsBuilder.UseSqlServer(connectionString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Planets>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.EnglishName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.RebelInfluence).HasColumnType("decimal(5, 2)");
            });

            modelBuilder.Entity<PricesHistory>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.PricePerLunarDay).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ValidFrom).HasColumnType("datetime");

                entity.Property(e => e.ValidTo).HasColumnType("datetime");
            });

            modelBuilder.Entity<Routes>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Distance).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

                entity.HasOne(d => d.DestinationPlanet)
                    .WithMany(p => p.RoutesDestinationPlanet)
                    .HasForeignKey(d => d.DestinationPlanetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Routes_Planets1");

                entity.HasOne(d => d.OriginPlanet)
                    .WithMany(p => p.RoutesOriginPlanet)
                    .HasForeignKey(d => d.OriginPlanetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Routes_Planets");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}